"""Regenerate data/structured/contract_terms.json from the agreement documents.

The runtime consumes a *structured entitlements registry* rather than parsing
legal text on every request — the same pattern real support platforms use. This
script is the compiler: it runs each signed agreement in the corpus through
Claude with a strict JSON schema, so the registry is derived from the source
documents, reviewable in diff, and reproducible when contracts change.

Usage: ANTHROPIC_API_KEY=... .venv/bin/python scripts/compile_contracts.py
The output is printed for review; pass --write to update the registry file.
"""

import json
import sys
from pathlib import Path

import anthropic

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from app import datastore  # noqa: E402

SCHEMA = {
    "type": "object",
    "properties": {
        "sla": {
            "type": ["object", "null"],
            "properties": {
                "source_clause": {"type": "string"},
                "P1": {"$ref": "#/$defs/target"},
                "P2": {"$ref": "#/$defs/target"},
                "P3": {"$ref": "#/$defs/target"},
                "coverage_notes": {"type": ["string", "null"]},
            },
            "required": ["source_clause", "P1", "P2", "P3"],
            "additionalProperties": False,
        },
        "cancellation": {
            "type": ["object", "null"],
            "properties": {
                "source_clause": {"type": "string"},
                "booked_fee_waived": {"type": "boolean"},
                "notes": {"type": "string"},
            },
            "required": ["source_clause", "booked_fee_waived"],
            "additionalProperties": False,
        },
        "service_credit": {
            "type": ["object", "null"],
            "properties": {
                "source_clause": {"type": "string"},
                "delay_threshold_hours": {"type": ["number", "null"]},
                "fixed_amount_inr": {"type": ["number", "null"]},
                "monthly_aggregate_cap_inr": {"type": ["number", "null"]},
                "requires_carrier_fault": {"type": ["boolean", "null"]},
                "requires_no_customer_fault": {"type": ["boolean", "null"]},
                "notes": {"type": ["string", "null"]},
            },
            "required": ["source_clause"],
            "additionalProperties": False,
        },
    },
    "required": ["sla", "cancellation", "service_credit"],
    "additionalProperties": False,
    "$defs": {
        "target": {
            "type": "object",
            "properties": {
                "amount": {"type": "number"},
                "unit": {"type": "string", "enum": ["minutes", "hours", "business_hours", "business_days"]},
                "coverage": {"type": ["string", "null"]},
            },
            "required": ["amount", "unit"],
            "additionalProperties": False,
        }
    },
}

PROMPT = """Extract the customer-specific entitlement overrides from this signed agreement.

Rules:
- Include ONLY terms this agreement itself grants or replaces. If the agreement defers
  to the standard policy/SOP for a topic (and adds nothing), set that section to null —
  except caps or notes it does add.
- Time units: plain minutes/hours mean wall-clock (24x7); "business hours/days" mean the
  business-hours clock. Preserve the distinction exactly as written.
- source_clause must name the agreement and section, e.g. "Northstar Enterprise Agreement §2".

AGREEMENT TEXT:
{text}"""


def main() -> None:
    client = anthropic.Anthropic()
    registry: dict = {
        "_comment": "Generated by scripts/compile_contracts.py — structured entitlements "
        "compiled from the signed agreements in the data pack. Review before committing."
    }
    for meta in datastore.doc_registry():
        if meta["doc_type"] != "agreement":
            continue
        text = (ROOT / "data" / "corpus" / meta["file"]).read_text(encoding="utf-8")
        response = client.messages.create(
            model="claude-opus-5",
            max_tokens=16000,
            messages=[{"role": "user", "content": PROMPT.format(text=text)}],
            output_config={"format": {"type": "json_schema", "schema": SCHEMA}},
        )
        extracted = json.loads(next(b.text for b in response.content if b.type == "text"))
        entry = {"source_doc": meta["doc_id"]}
        entry.update({k: v for k, v in extracted.items() if v is not None})
        registry[meta["account_id"]] = entry
        print(f"Compiled {meta['title']} -> {meta['account_id']}")

    output = json.dumps(registry, indent=2)
    if "--write" in sys.argv:
        (ROOT / "data" / "structured" / "contract_terms.json").write_text(output + "\n")
        print("Wrote data/structured/contract_terms.json")
    else:
        print(output)
        print("\n(Dry run — pass --write to update the registry.)")


if __name__ == "__main__":
    main()
